#!/usr/bin/env bash
# Use a for loop to iterate over numbers from 1 to 100
for ((i=1; i<=100; i++)); do
    # Check for multiples of both 3 and 5
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    # Check for multiples of 3
    elif ((i % 3 == 0)); then
        echo "Fizz"
    # Check for multiples of 5
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo $i
    fi
done
