#!/usr/bin/env bash
# Initialize a counter
counter=1

# Using a while loop to loop from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        4)
            # Display "4 and bad luck from China" for the 4th iteration
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            # Display "9 and bad luck from Japan" for the 9th iteration
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            # Display "17 and bad luck from Italy" for the 17th iteration
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            # Display the current number for other iterations
            echo $counter
            ;;
    esac

    ((counter++))
done
